osx_instance:
  image:             mojave-xcode-10.2-flutter

container:
  image:             cirrusci/flutter:latest

task:
  name:              setup
  environment:
    FIREBASE_SECRET: ENCRYPTED[fe7dd7e24bbefac9fd30db714f6c7926cbd7da6f2e746cef91e288dbd82d83d9224c12f14e8167cccef1869e1c582197]
  script:
    - cp ios/Runner/GoogleService-Info-sample.plist ios/Runner/GoogleService-Info.plist
    - plutil -replace API_KEY -string "$FIREBASE_SECRET" ios/Runner/GoogleService-Info.plist

lint_task:
  script:            flutter analyze

test_task:
  environment:
    GVUSER:          ENCRYPTED[f7e5b797c0913a581bbaccdeb712b4e0a35df2811940f30a7cab5c4798689e3c02f6daaf5cb08bc2dd5bc98c768171a9]
    GVPASS:          ENCRYPTED[f19cae5784d8d8294da67e1ff5fa1bd163bb7e9d17f01251321d217cebdf61ec64a938834de66a8f8cebeb1930cb0978]
  pub_cache:
    folder:          ~/.pub-cache
  test_script:       flutter test

task:
  name:              build
  script:
    - flutter build bundle
    - flutter build appbundle
    - flutter build aot
    - flutter build apk
    - flutter build ios
