os:
- linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
git:
  depth: 1
cache:
  directories:
  - "$HOME/.pub-cache"
env:
  matrix:
  - FLUTTER_VERSION=stable
  - FLUTTER_VERSION=dev
  global:
  - secure: ZNv9n5GYhH8W8Yux3L3h1w1qQUsGgh+2dZp9U9kDYvADk3nR2tCIbKA0zWaweo5SitVuHz983CNmGyZtsjr0CfjRl7uZS4jFS63P7Qe4O23KU9FkMx1Jwu7XCsgEvzhFBKfhLs/rzO1E/fWRwQMQ7LeeMXhV0/bF3N6BPKk2jJyQARkXKh4DlL7CrBt8UuQSargRDlRlTnicBFCtMuhoq6LW7wk4FTURueopz4kW4iwc/qqh2eMxYIl1WeFy7R/zp4D2kw8nC0g3ntaul5qZgmZeTGFshEkxLns4/W2FwWZaI9KFowyWyURUXTDCbr9cE4K1U6ctiRr8TNZTNveP5PRcD9jaIHuBUhZjxojG2338PevEjR7t1RMvYA+zvkPX8vNCNI9RWMmiEKRK/ux8s+Y4pMKTVgpmuobzd2g4ltVzrIkem1ZqRW+9RBWjYZQWTc1sQ3SkQoAHvPsY/WBHbc4ojV5l4H2zYfFOwg95W2D0NVENosl3RfdI0GLZAvIEAaEbRUernyx0hch16Z20ilPhjsm9hsBM39YOH4uiesDhB1kHhWE1OWGMnbAH4f859lTS5P1uG2JTyvS6x/QgrTyMbldToL1TRkTKUuRgS4kVMT2VP2ZAsa/tp5/4jLh1R3XxD8oVN5PSCu49/87L1fTWYHA3SOdTkMYy5g2gUq0=
  - secure: D2nglE3Y3rKVuF6GBU1Yrdp4ScsM0A69CBlLw7zgeAEpDLf7ysX+4CYaMGJXtabHeYhEmIomvI09TguQmgax89uNod4pm1l/Vs0MURtWAmA8VXesK3N1tKZqzNyUB0ggXYG0xTlDHv1+RuWl0WJLuR58JFk9s8cknPiQlgdD/HNCAqeKxCnvHeaX6JeW/10/L4KmZ14N1hv+hmeFVDPir3Qgkbm8wQMzHsNz4T3OYoYo5aq9xYcGUNgxQ/g36yqJsgj3YIAwJU6msjwiqqgew0/ndXPkx68czWPlv/Bfq2SenndHDfrYMT3dba5cteTZqY/RZq8SxFbJeSwxIxXR7f+GL9VSALoMRmK6Y0Bk9RwZgSkGSC5+nsKpAz6ovW2X15gaZDDuVvyw+0Sv6VqnlfFdmQ30v6Jq/xz8bXUM6rHrPmHIyD895/nk0JRXDfDgfTe/Di67oS7/yIdpsNiq5M4skDXxCgq4yZryyErFWqNxdOTBK24VfoCysMZ60SDRb0shsgJOzDWPfpG5Y702n2FpEZLSEOgBN3zuM5NZEOjSsDUH0Kdl3GIENgqlkRI//G1KxbawxeZNAwb5ZwuAVrJnJCeABxGMR29DgjvOV/vQl2/wO+Q25j4HRdGo4gc8QW8iEK8T3zaDajTFJSojfy1m3zOobkB/dsbnQE7jwY8=
matrix:
  allow_failures:
  - env: FLUTTER_VERSION=dev
before_script:
- git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
- "./flutter/bin/flutter doctor"
script:
- ls -lh
- "./flutter/bin/flutter test"
- "./flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run lib/"
- "./flutter/bin/cache/dart-sdk/bin/dartfmt --dry-run test/"
