name:                          grade_view
description:                   'an app for FCPS SIS with lots of additional functionality'
author:                        'S Ratna <sratna@sumanthratna.gq>'
repository:                    'https://github.com/sumanthratna/grade-view'
issue_tracker:                 'https://github.com/sumanthratna/grade-view/issues'
version:                       1.0.7
environment:
    sdk:                       '>=2.0.0 <3.0.0'
dependencies:
    flutter:
        sdk:                   flutter
    http:                      ^0.12.0+2
    flutter_secure_storage:    ^3.2.1+1
    firebase_messaging:        ^4.0.0+3
    modal_progress_hud:        ^0.1.3
    datetime_picker_formfield: ^0.1.8
    decimal:                   ^0.3.3
    cupertino_icons:           ^0.1.2
    flutter_typeahead:         ^1.5.0
dev_dependencies:
    flutter_test:
        sdk:                   flutter
flutter:
    uses-material-design:      true
    assets:
        - assets/fcps.png
